export default [
    "Chuck Norris a déjà compté jusqu'à l'infini. Deux fois.",
    "Google, c'est le seul endroit où tu peux taper Chuck Norris",
    "Certaines personnes portent un pyjama Superman. Superman porte un pyjama Chuck Norris",
    "Chuck Norris donne fréquemment du sang à la Croix-Rouge. Mais jamais le sien.",
    "Chuck Norris et Superman ont fait un bras de fer, le perdant devait mettre son slip par dessus son pantalon.",
    "Chuck Norris ne se mouille pas, c'est l'eau qui se Chuck Norris.",
    "Chuck Norris peut gagner une partie de puissance 4 en trois coups.",
    "Un jour, Chuck Norris a perdu son alliance. Depuis c'est le bordel dans les terres du milieu...",
    "Jesus Christ est né en 1940 avant Chuck Norris.",
    "Chuck Norris ne porte pas de montre. Il décide de l'heure qu'il est.",
    "La seule chose qui arrive à la cheville de Chuck Norris... c'est sa chaussette.",
    "Chuck Norris fait pleurer les oignons.",
    "Dieu a dit: que la lumiere soit! et Chuck Norris répondit : On dit s'il vous plait.",
    "Chuck Norris peut diviser par zéro.",
    "Chuck Norris comprend Jean-Claude Van Damme.",
    "Chuck Norris sait parler le braille.",
    "Chuck Norris a un jour avalé un paquet entier de somnifères. Il a cligné des yeux.",
    "Quand Google ne trouve pas quelque chose, il demande à Chuck Norris.",
    "Les suisses ne sont pas neutres, ils attendent de savoir de quel coté Chuck Norris se situe.",
    "Il n'y a pas de théorie de l'évolution. Juste une liste d'espèces que Chuck Norris autorise à survivre.",
    "Chuck Norris peut encercler ses ennemis. Tout seul.",
    "Chuck Norris est la raison pour laquelle Charlie se cache.",
    "Chuck Norris a déjà été sur Mars, c'est pour cela qu'il n'y a pas de signes de vie là bas.",
    "Quand Chuck Norris sest mis au judo, David Douillet s'est mis aux pièces jaunes.",
    "Un jour, au restaurant, Chuck Norris a commandé un steak. Et le steak a obéi."
];